version: "3.8"

services:

  web:
    image: nginx:stable
    depends_on:
      - api
    restart: always
    ports:
    - "8080:80"
    environment:
    - DJANGO_HOST=app
    volumes:
      - static:/static
      - media:/media
#      - /default.conf:/etc/nginx/conf.d/
      - ./default.conf:/etc/nginx/conf.d/default.conf
#    - ./www:/www
    networks:
    - backend

  api:
    build: .
    image: gysborn/dm_pythoncheat
    restart: always
    ports:
    - "8000:8000"
    volumes:
    - .:/app
    - static:/app/static
    - media:/app/media
    networks:
    - backend
volumes:
  static:
  media:

networks:
    backend: