# Generated by Django 4.1.5 on 2023-02-03 19:44

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Видео'),
        ),
    ]
