# Generated by Django 4.1.5 on 2023-02-09 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        ('dj', '0002_dj_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.chapters'),
        ),
        migrations.AddField(
            model_name='dj',
            name='code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
