# Generated by Django 4.1.5 on 2023-02-11 19:53

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        ('dj', '0007_dj292'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dj',
            name='label',
        ),
        migrations.RemoveField(
            model_name='dj272',
            name='label',
        ),
        migrations.RemoveField(
            model_name='dj280',
            name='label',
        ),
        migrations.RemoveField(
            model_name='dj291',
            name='label',
        ),
        migrations.RemoveField(
            model_name='dj292',
            name='label',
        ),
        migrations.CreateModel(
            name='Dj301',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=1000, null=True)),
                ('slug', models.SlugField(null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('git', models.CharField(blank=True, max_length=100, null=True)),
                ('colab', models.CharField(blank=True, max_length=100, null=True)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, verbose_name='Видео')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.chapters')),
            ],
        ),
    ]
