# Generated by Django 4.1.5 on 2023-03-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_ts132_ts131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ts132',
        ),
    ]
