# Generated by Django 4.1.5 on 2023-08-16 17:48

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ide',
            name='video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
