# Generated by Django 4.1.5 on 2023-11-14 15:59

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0004_ide_env_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ide_env',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Видео'),
        ),
    ]
