# Generated by Django 4.1.5 on 2023-11-14 16:03

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0005_alter_ide_env_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ide',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='ide_env_com',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Видео'),
        ),
    ]
