# Generated by Django 4.1.5 on 2023-07-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker', '0002_d262'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d252',
            name='code',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='d252',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='d252',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
