# Generated by Django 4.1.5 on 2023-07-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker', '0003_alter_d252_code_alter_d252_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d262',
            name='code',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='d262',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='d262',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
